sudo: required
language: java
jdk: oraclejdk8
addons:
  ssh_known_hosts:
  - 47.93.9.236:22008
  sonarcloud:
    organization: tron-zhaohong
    token:
      secure: "KXWEeQ1elAoQ0XfR54TQWfhrIdDP0+2CYPv2X9aWpU/YDl7hqZBAjcCOAUGvlbyM54jtG6YMaWwG48jlrOwwl5l/VjWSnUXF+7ixQy5ki0Ci9s7Y1pTQwV9SpL8TLIK2TYqabN8Mw+FJULASXLjYr9GerbbcUbCPTmcL6mQKw6ivxxpNPmz4eNoKAEuOzruO9fTXGAV3yr8Nn85c+mVxV8EUhkR17zpE9O8fvzOtSnYArWNOSCgDBn0EG45UNNPF2vn44s1c3h3gX1m3WK6PeCXPgy3hPqRn3wTG+xglnbqthGpo2wt1rJ83af+BwdYwvPEcUq84yLgXcE/aMkTKcVAfPWBP/6vblaoI90jxCeFji+MdMimKZAqIXt7oLqDZVmIq65de5YC5s7QTSbzJNY/tsAu3dqzSfbUJY6CRNFDcoenVpvgQkqb37TkDah4mJM8EUjbu2A9Q2HSFbyCVsQJtdasuu9cBOf6azK3U0XgFNBc0y2aziZrTnX30q7bi+5L/mbTnRdXrDqBOqyPeGtT77UZfcajHHmEWU/e6gYWiA/c+K25n13DD53Au6gpnnQ6ALeUl/1gDwz3fPBebJ5bVWrkIcLj7bbysjzfOvQmDS6G13RNz58Hm0/B7bVtZTr1E1q6Z1zEJwbuJYEJASNcezAfK5x/hIfZTGNqT3M8="
cache:
  directories:
    - '$HOME/.sonar/cache'
script:
- sh tron.sh
- "./gradlew build"

skip_build:
- README.md：
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
after_deploy:
- "./gradlew stest"

notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=e53bf02346738c483a624d092eb468cf653ec8747537d085c5d84728d6bd65cf
    on_success: never # default: change
    on_failure: always # default: always
    on:
      branch: develop